steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/chaos-demo', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/chaos-demo']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'chaos-demo', '--image', 'gcr.io/$PROJECT_ID/chaos-demo', '--region', 'us-west1', '--allow-unauthenticated', '--timeout','50m', '--no-cpu-throttling', '--memory', '2Gi', '--cpu', '4']
images:
- gcr.io/$PROJECT_ID/chaos-demo
options:
 machineType: 'E2_HIGHCPU_8'